name: Monday Fights Downloader

on:
  workflow_dispatch:
  schedule:
      - cron: '45 20 * * MON' # UTC time fifteen minutes after Monday Fight

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 19
      - name: Use token
        env:
          TOKEN: ${{ secrets.MONDAY_FIGHTS_TOKEN }} # we need personal token because default GITHUB_TOKEN never triggers new events so pages would not be rebuilt
        run: |
          # Download Monday Fights
          cd Scripts
          node downloadMF.mjs
          git config --global user.name 'Bebul BOT'
          git config --global user.email 'Bebul@users.noreply.github.com'
          if git diff --exit-code --quiet; then 
            echo Up to date, nothing to commit!
          else 
            git commit -am "Regular Monday Fights tournament download"
            git push
          fi
